blank_issues_enabled: false
contact_links:
  - name: Support and Questions
    about: Do not open issues for questions, instead visit our support section.
    url: https://github.com/{{ cookiecutter.vcs_path }}/blob/master/docs/SUPPORT.md